### ISSUE TITLE
Its get "Network Error" when image is too big.

### ISSUE THREAD

**Issue by pftom** [dhucst/MILL#3]
Issue recurrence:

- Upload a `2.7 MB` jpg
- Do some labels
- Download `json` file, show up `Failed - Network Error`

![image](https://user-images.githubusercontent.com/26423749/49323334-932c1d80-f554-11e8-9f44-f680f494b9f4.png)

**Comment by mrcfps** [comment]
@pftom I've reproduced this bug too. Quite confusing.

**Comment by pftom** [comment]
@mRcfps  I already fixed this.✌️
